### ISSUE TITLE
Composer - installation error

### ISSUE THREAD

**Issue by nope123nope** [sebdesign/laravel-state-machine#43]
Hi, i have some problems with installation 

My Composer configs 

```
"laravel/framework": "^6.2",
"php": "^7.2",
```
 
Output on installation: 

```composer require sebdesign/laravel-state-machine ^2.0
./composer.json has been updated
Loading composer repositories with package information 
Updating dependencies (including require-dev)         
Fatal error: Allowed memory size of 1610612736 bytes exhausted 
(tried to allocate 4096 bytes) 
in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php 
on line 223
```

**Comment by sebdesign** [comment]
I'm not sure why the memory is exhausted, but you can try this command on your terminal:

`COMPOSER_MEMORY_LIMIT=-1 composer update`

**Comment by scottzirkel** [comment]
Was having the same issues, forgot about the memory limit setting, thanks!

Update: I don't think this issue is truly related to your package, but I first got it when trying to install it. Seems to be another issue that only looked to be related to this package. Still a helpful command to sort out issues.

**Comment by nope123nope** [comment]
Thanks, it works for me. 
Building composer vendors in okteto docker containter - memory was limited also in configs.
Closing issue.

**Comment by sebdesign** [comment]
Maybe it's because this package requiring a fork of `winzou/state-machine` instead of the original package.
