### ISSUE TITLE
Idea: Easy notify on before and after events

### ISSUE THREAD

**Issue by eduardoarandah** [sebdesign/laravel-state-machine#9]
A common scenario is notifying on transitions. 

Right now it works like this

```

// will be called before applying a transition
            'before' => [],

            // will be called after applying a transition
            'after'  => [
                [
                    'on' => 'solicitar_exponer',
                    'do' => function ($event) {
                        $event->getStateMachine()->getObject()->notify(new App\Notifications\ExposicionNotification($event));
                    },
                ],
```

Do you think it would add value to notify easier? 

something like:

                [
                    'on' => 'solicitar_exponer',
                    'notify' => 'ExposicionNotification',
                ],

Always calling ->notify on the object being transitioned
and passing the caller and transitionEvent as arguments. 

Do you think it would add value? or is it too specific?

**Comment by sebdesign** [comment]
This is a common scenario indeed, when you want to to send notification when an event is fired (not only regarding state machines).

You can simplify your code a bit like this:

```php
'after' => [
    [
        'on' => 'solicitar_exponer',
        'do' => function ($event, $user) {
            $user->notify(new App\Notifications\ExposicionNotification($event));
        },
        'args' => ['event', 'object'],
    ],
],
```

I don't think it's ideal to put anonymous functions in config, because they can't be cached using `php artisan config:cache`.

One solution would be to use event listeners:
In `App\Providers\EventServiceProvider.php`:

```php
protected $listen = [
    SMEvents::POST_TRANSITION => [
        \App\Listeners\AfterTransition::class,
    ],
];
```
In `App\Listeners\AfterTransition.php`:
```php
public function handle($event) {
    if ($event->getTransition() == 'solicitar_exponer') {
        $event->getStateMachine()->getObject()->notify(new App\Notifications\ExposicionNotification($event));
    }
}
```

But if you have many transitions or state machines, that could become ugly.

Another solution would be to define custom events (as strings or classes) for transitions:

In `App\Providers\EventServiceProvider.php`:
```php
public function register() {
    Event::listen('solicitar_exponer', function ($event) {
        $event->getStateMachine()->getObject()->notify(new App\Notifications\ExposicionNotification($event));
    });
}
```

Or using the `$listen` array with a class listener: 

In `App\Providers\EventServiceProvider.php`:
```php
protected $listen = [
    'solicitar_exponer' => [
            \App\Listeners\SendExposicionNotification::class,
        ],
    ];
}
```

You can use the same approach with event subscribers to group similar events together.

Finally, in your state machine config I guess you can do this:
```php
'after' => [
    [
        'on' => 'solicitar_exponer',
        // this will call the `event` helper of Laravel
        'do' => 'event',
        // and fire the `solicitar_exponer` event with the `$event` instance
        'args' => ['"solicitar_exponer"', 'event'],
    ],
],
```

**Comment by flo-sch** [comment]
Hey @sebdesign, nice input about using EventListeners :)

But I guess it would not allow the Listener class to be type-hinted?

How could I inject the Request object for instance?

```
// App\Providers\EventProvider.php
protected $listen = [
    'my_event' => [
        'App\Listeners\MyListener@myMethod',
    ],
];
```

```
// App\Listeners\MyListener
public function myMethod(\SM\Event\TransitionEvent $event, \Illuminate\Http\Request $request)
{
    // ...
}
```

**Comment by sebdesign** [comment]
Generally, Laravel resolves the listener classes through the container, so you can pass the `Illuminate\Http\Request` into the constructor of `App\Listeners\MyListener` and it will be injected automatically.

```php
<?php

namespace App\Listeners;

use Illuminate\Http\Request;

class MyListener
{
    protected $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function myMethod(\SM\Event\TransitionEvent $event)
    {
        // ...
    }
```

Or just use the `request()` helper in your method, it will give you an instance of the request.

**Comment by flo-sch** [comment]
Very clear, thank you :)
